#!/usr/bin/env bash
# Quick start guide for Job Management System

echo "Job Management System - Quick Start"
echo "===================================="
echo ""
echo "Files created:"
echo "  - src/core/job.py                 (Job class)"
echo "  - src/tools/jobs/__init__.py       (JobManager class)"
echo "  - src/tools/jobs/examples.py       (Usage examples)"
echo "  - src/tools/jobs/README.md         (Documentation)"
echo "  - tests/core/test_job.py           (Job tests)"
echo "  - tests/tools/test_jobs.py         (JobManager tests)"
echo ""
echo "Quick start:"
echo ""
echo "1. Create a job:"
echo "   from tools.jobs import JobManager"
echo "   manager = JobManager()"
echo "   job = manager.create_job('my_job')"
echo "   job.start()"
echo ""
echo "2. Execute agents synchronously:"
echo "   result = job.call_agent_sync(agent, input_data)"
echo ""
echo "3. Queue agents asynchronously:"
echo "   task_id = job.call_agent_async(agent, queue, input_data)"
echo ""
echo "4. Complete and save:"
echo "   job.complete(results)"
echo "   job.save_metadata()"
echo ""
echo "5. Load job later:"
echo "   job = manager.get_job('my_job')"
echo "   print(job.status, job.results)"
echo ""
echo "Job storage location:"
echo "   ~/.cresus/db/jobs/<job_name>/"
echo ""
echo "Files per job:"
echo "   config.yml     - Job configuration"
echo "   metadata.json  - Job metadata (status, results, etc)"
echo "   job.log        - Job log file"
echo ""
echo "Run examples:"
echo "   cd src/tools/jobs"
echo "   python examples.py"
echo ""
echo "Run tests:"
echo "   pytest tests/core/test_job.py -xvs"
echo "   pytest tests/tools/test_jobs.py -xvs"
