"""Transaction agent for executing pending orders and managing exits on a specific date."""

from datetime import datetime, date as date_type
from typing import Any, Dict, Optional, List
import json
from core.agent import Agent
from tools.portfolio import PortfolioManager
from tools.portfolio.orders import Orders
from tools.portfolio.journal import Journal
from tools.portfolio.broker import PaperBroker
from tools.strategy import StrategyManager
from .sub_agents import (
	StopLossAgent,
	TargetAgent,
	TimeLimitAgent,
	LimitOrderAgent,
)


class TransactAgent(Agent):
	"""Agent for executing pending orders on a specific trading date.

	Executes pending orders generated by ExitAgent and EntryOrderAgent:
	1. Execute SELL orders (from exit conditions) at market prices
	2. Execute limit orders (conditional BUY orders)
	3. Execute BUY orders (market orders)
	4. Check open positions against stop_loss, take_profit, time limits
	5. Record all transactions in journal
	6. Update portfolio cache
	"""

	def __init__(self, name: str = "TransactAgent", context: Optional[Any] = None):
		"""Initialize transact agent.

		Args:
			name: Agent name
			context: AgentContext for shared state
		"""
		super().__init__(name, context)
		self.stop_loss_agent = StopLossAgent("StopLossAgent")
		self.target_agent = TargetAgent("TargetAgent")
		self.time_limit_agent = TimeLimitAgent("TimeLimitAgent")
		self.limit_agent = LimitOrderAgent("LimitOrderAgent")

	def process(self, input_data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
		"""Execute pending BUY orders and manage exits (stop_loss) for a specific date.

		Assumes day data has already been loaded by TransactFlow into context.data_history.

		Args:
			input_data: Input data with:
				- date: Trading date (YYYY-MM-DD or date object)
				- portfolio_name: Portfolio to execute orders for

		Returns:
			Response with execution results (BUY and EXIT)
		"""
		if input_data is None:
			input_data = {}

		# Get parameters from context (set by TransactFlow)
		portfolio_name = self.context.get("portfolio_name") or "default"
		trading_date = self.context.get("date")

		if not trading_date:
			return {
				"status": "error",
				"input": input_data,
				"message": "date not set in context"
			}

		# Get pre-sliced day data (already filtered to specific date by BacktestAgent)
		day_data = self.context.get("day_data") or {}
		if not day_data:
			self.logger.warning(f"No day data available for {trading_date}")

		journal = Journal(portfolio_name, context=self.context.__dict__)
		orders_mgr = Orders(portfolio_name, context=self.context.__dict__)

		# Execute SELL orders first (from exit conditions)
		sell_results = self._execute_sell_orders(
			orders_mgr,
			journal,
			portfolio_name,
			trading_date,
			day_data
		)

		# Execute buy orders in priority: limit orders first, then market orders
		buy_results = []

		# 1. Execute limit orders (these stay pending until price condition met)
		self.limit_agent.context = self.context
		limit_result = self.limit_agent.process({"day_data": day_data})
		buy_results.extend(limit_result.get("output", {}).get("orders", []))

		# 2. Execute market orders (remaining pending orders)
		market_results = self._execute_buy_orders(
			orders_mgr,
			journal,
			portfolio_name,
			trading_date,
			day_data
		)
		buy_results.extend(market_results)

		# Load strategy config to get holding_period for exits (if not already set)
		if not self.context.get("holding_period"):
			strategy_name = self.context.get("strategy_name")
			if strategy_name:
				try:
					sm = StrategyManager()
					result = sm.load_strategy(strategy_name)
					strategy_config = result.get("data", {}) if result.get("status") == "success" else {}
					if strategy_config and "exit" in strategy_config:
						exit_config = strategy_config.get("exit", {})
						if "parameters" in exit_config and "holding_period" in exit_config["parameters"]:
							hp_formula = exit_config["parameters"]["holding_period"].get("formula")
							if hp_formula:
								try:
									holding_period = int(float(hp_formula))
									self.context.set("holding_period", holding_period)
									self.logger.debug(f"Set holding_period to {holding_period} from strategy config")
								except (ValueError, TypeError):
									pass
				except Exception as e:
					self.logger.debug(f"Could not load holding_period from strategy: {e}")

		# Execute exit orders via subagents in sequence
		exit_results = []

		# 1. Stop loss exits
		self.stop_loss_agent.context = self.context
		stop_loss_result = self.stop_loss_agent.process({"day_data": day_data})
		exit_results.extend(stop_loss_result.get("output", {}).get("exits", []))

		# 2. Take profit exits (only if enabled in strategy)
		take_profit_enabled = self._is_take_profit_enabled()
		if take_profit_enabled:
			self.target_agent.context = self.context
			target_result = self.target_agent.process({"day_data": day_data})
			exit_results.extend(target_result.get("output", {}).get("exits", []))
		else:
			self.logger.info("Take profit is disabled in strategy, skipping target agent")

		# 3. Time limit exits (unfilled entry orders)
		self.time_limit_agent.context = self.context
		time_limit_result = self.time_limit_agent.process({"day_data": day_data})
		exit_results.extend(time_limit_result.get("output", {}).get("exits", []))

		buy_count = len([r for r in buy_results if r.get("status") == "filled"])
		exit_count = len([r for r in exit_results if r.get("status") == "filled"])
		total_executed = buy_count + exit_count

		# Update portfolio cache
		pm = PortfolioManager(context=self.context.__dict__)
		pm.update_portfolio_cache(portfolio_name)

		return {
			"status": "success",
			"input": input_data,
			"output": {
				"portfolio": portfolio_name,
				"date": trading_date.isoformat(),
				"buy_executed": buy_count,
				"exit_executed": exit_count,
				"total_executed": total_executed,
				"buy_details": buy_results,
				"exit_details": exit_results,
			},
			"message": f"Executed {buy_count} BUY + {exit_count} EXIT orders for {portfolio_name}",
		}

	def _execute_sell_orders(
		self,
		orders_mgr: Orders,
		journal: Journal,
		portfolio_name: str,
		trading_date: date_type,
		day_data: Dict[str, Any]
	) -> List[Dict[str, Any]]:
		"""Execute pending SELL orders using market data.

		Args:
			orders_mgr: Orders manager
			journal: Journal for recording transactions
			portfolio_name: Portfolio name
			trading_date: Date of execution
			day_data: Pre-sliced market data {ticker: row} for the specific date

		Returns:
			List of sell execution results
		"""
		execution_results = []
		broker = PaperBroker()
		pending_orders = orders_mgr.get_pending_orders()

		if pending_orders.empty:
			return execution_results

		# Filter for SELL orders only (marked in metadata with order_type="SELL")
		sell_orders = []
		for _, order_row in pending_orders.iterrows():
			try:
				import json
				metadata = order_row.get("metadata", "")
				if metadata:
					metadata_dict = json.loads(metadata) if isinstance(metadata, str) else metadata
					if metadata_dict.get("order_type") == "SELL":
						sell_orders.append((_, order_row))
			except (json.JSONDecodeError, TypeError):
				pass

		if not sell_orders:
			return execution_results

		try:
			for _, order_row in sell_orders:
				order_id = str(order_row.get("id", ""))
				ticker = str(order_row.get("ticker", ""))
				quantity = int(order_row.get("quantity", 0))

				# Get market price for the date
				market_price = self._get_market_price(ticker, day_data)
				if market_price is None:
					self.logger.warning(f"No market price for {ticker}, skipping SELL order")
					orders_mgr.update_order_status(order_id, "rejected")
					continue

				execution_price = market_price

				# Convert order for broker
				broker_order = {
					"ticker": ticker,
					"quantity": quantity,
					"action": "SELL",
					"price": execution_price,
					"strategy_id": "transact",
				}

				# Execute through broker
				result = broker.execute_order(broker_order)

				execution_result = {
					"order_id": order_id,
					"ticker": ticker,
					"quantity": quantity,
					"execution_price": execution_price,
					"status": result.status,
					"filled_price": result.filled_price,
					"filled_quantity": result.filled_quantity,
					"reason": result.reason,
				}
				execution_results.append(execution_result)

				# Update order status and record transaction if filled
				if result.status == "filled":
					orders_mgr.update_order_status(order_id, "executed")

					# Extract exit_type from metadata (stored as JSON string)
					exit_type = None
					try:
						metadata_str = order_row.get("metadata", "")
						if metadata_str:
							metadata_dict = json.loads(metadata_str) if isinstance(metadata_str, str) else metadata_str
							exit_type = metadata_dict.get("exit_type")
					except (json.JSONDecodeError, TypeError):
						pass

					# Record SELL transaction in journal
					journal.add_transaction(
						operation="SELL",
						ticker=ticker,
						quantity=result.filled_quantity,
						price=result.filled_price,
						fees=0,
						notes=f"Order {order_id[:8]} executed",
						created_at=f"{trading_date.isoformat()}T14:00:00.000000",
						exit_type=exit_type
					)

					self.logger.info(
						f"SELL {result.filled_quantity} {ticker} @ {result.filled_price:.2f} "
						f"(order {order_id[:8]})"
					)
				else:
					orders_mgr.update_order_status(order_id, "rejected")
					self.logger.warning(f"SELL Order {order_id[:8]} rejected: {result.reason}")

		except Exception as e:
			self.logger.error(f"Error executing SELL orders: {e}")

		return execution_results

	def _execute_buy_orders(
		self,
		orders_mgr: Orders,
		journal: Journal,
		portfolio_name: str,
		trading_date: date_type,
		day_data: Dict[str, Any]
	) -> List[Dict[str, Any]]:
		"""Execute pending BUY orders using market data.

		Args:
			orders_mgr: Orders manager
			journal: Journal for recording transactions
			portfolio_name: Portfolio name
			trading_date: Date of execution
			day_data: Pre-sliced market data {ticker: row} for the specific date

		Returns:
			List of buy execution results
		"""
		execution_results = []
		broker = PaperBroker()
		pending_orders = orders_mgr.get_pending_orders()

		if pending_orders.empty:
			return execution_results

		try:
			for _, order_row in pending_orders.iterrows():
				order_id = str(order_row.get("id", ""))
				ticker = str(order_row.get("ticker", ""))
				execution_method = str(order_row.get("execution_method", "market"))

				# Skip SELL orders (handled by _execute_sell_orders)
				is_sell_order = False
				try:
					metadata_str = order_row.get("metadata", "")
					if metadata_str:
						metadata_dict = json.loads(metadata_str) if isinstance(metadata_str, str) else metadata_str
						is_sell_order = metadata_dict.get("order_type") == "SELL"
				except (json.JSONDecodeError, TypeError, AttributeError):
					pass

				if is_sell_order:
					continue

				# Skip limit orders (handled by LimitOrderAgent)
				if execution_method == "limit":
					continue

				quantity = int(order_row.get("quantity", 0))
				entry_price = float(order_row.get("entry_price", 0))
				stop_loss = float(order_row.get("stop_loss", 0)) if order_row.get("stop_loss") else None
				take_profit = float(order_row.get("take_profit", 0)) if order_row.get("take_profit") else None
				trailing_stop_distance = float(order_row.get("trailing_stop_distance", 0)) if order_row.get("trailing_stop_distance") else None

				# Get market price for the date (day_data is {ticker: row}, pre-sliced)
				market_price = self._get_market_price(ticker, day_data)
				if market_price is None:
					market_price = entry_price

				# Execute at better of entry_price or market price
				execution_price = market_price

				# Validate and adjust stop_loss/take_profit based on execution price
				# If order was created on a previous day, these values might be stale
				if stop_loss and stop_loss >= execution_price:
					# Stop loss is above execution price - recalculate based on risk ratio
					if take_profit and execution_price > 0:
						risk_ratio = (take_profit - entry_price) / (entry_price - stop_loss) if (entry_price - stop_loss) != 0 else 1.0
						# Recalculate stop_loss to maintain proper risk management
						stop_loss = execution_price * 0.97  # 3% below execution price as safe default
				if take_profit and take_profit <= execution_price:
					# Take profit is below or at execution price - recalculate
					take_profit = execution_price * 1.05  # 5% above execution price as safe default

				# Convert order for broker
				broker_order = {
					"ticker": ticker,
					"quantity": quantity,
					"action": "BUY",
					"price": execution_price,
					"stop_loss": stop_loss,
					"target_price": take_profit,
					"strategy_id": "transact",
				}

				# Execute through broker
				result = broker.execute_order(broker_order)

				execution_result = {
					"order_id": order_id,
					"ticker": ticker,
					"quantity": quantity,
					"entry_price": entry_price,
					"execution_price": execution_price,
					"status": result.status,
					"filled_price": result.filled_price,
					"filled_quantity": result.filled_quantity,
					"reason": result.reason,
				}
				execution_results.append(execution_result)

				# Update order status and record transaction if filled
				if result.status == "filled":
					orders_mgr.update_order_status(order_id, "executed")

					# Record BUY transaction in journal with stop loss, take profit, and trailing stop
					journal.add_transaction(
						operation="BUY",
						ticker=ticker,
						quantity=result.filled_quantity,
						price=result.filled_price,
						fees=0,
						stop_loss=stop_loss,
						take_profit=take_profit,
						trailing_stop_distance=trailing_stop_distance,
						highest_price=result.filled_price,
						notes=f"Order {order_id[:8]} executed",
						created_at=f"{trading_date.isoformat()}T14:00:00.000000"
					)

					self.logger.info(
						f"BUY {result.filled_quantity} {ticker} @ {result.filled_price:.2f} "
						f"(order {order_id[:8]}) [SL: {stop_loss}]"
					)
				else:
					orders_mgr.update_order_status(order_id, "rejected")
					self.logger.warning(f"Order {order_id[:8]} rejected: {result.reason}")

		except Exception as e:
			self.logger.error(f"Error executing BUY orders: {e}")

		return execution_results

	def _get_market_price(self, ticker: str, day_data: Dict[str, Any]) -> Optional[float]:
		"""Get closing price for ticker from day data.

		Args:
			ticker: Ticker symbol
			day_data: Pre-sliced market data {ticker: row}

		Returns:
			Closing price or None
		"""
		if ticker not in day_data:
			return None

		row = day_data[ticker]
		try:
			return float(row.get("close")) if "close" in row else None
		except (ValueError, AttributeError):
			return None

	def _is_take_profit_enabled(self) -> bool:
		"""Check if take_profit is enabled in strategy configuration.

		In backtest mode, reads strategy config from strategy_name in context.
		In paper trading mode, conservatively enables take_profit (allows TargetAgent to check).

		Returns:
			True if take_profit should be evaluated, False if disabled
		"""
		strategy_name = self.context.get("strategy_name")
		if not strategy_name:
			# No strategy context (e.g., paper trading) - allow target agent to run
			self.logger.debug("No strategy_name in context, enabling take_profit")
			return True

		try:
			from tools.strategy.strategy import StrategyManager
			manager = StrategyManager()
			result = manager.load_strategy(strategy_name)
			
			if result.get("status") != "success":
				self.logger.warning(f"Could not load strategy config for {strategy_name}, enabling take_profit")
				return True
			
			strategy_config = result.get("data", {})
			if not strategy_config:
				self.logger.warning(f"Empty strategy config for {strategy_name}, enabling take_profit")
				return True

			# Check if take_profit is explicitly disabled
			exit_params = strategy_config.get("exit", {}).get("parameters", {})
			take_profit = exit_params.get("take_profit", {})

			# If formula is 'False' (string) or False (bool), it's disabled
			formula = take_profit.get("formula")
			is_disabled = formula == "False" or formula is False
			
			self.logger.info(f"Strategy {strategy_name}: take_profit.formula={repr(formula)}, disabled={is_disabled}")
			
			if is_disabled:
				return False

			return True
		except Exception as e:
			self.logger.warning(f"Error checking take_profit enabled: {e}, assuming enabled")
			return True
