portfolios:
- currency: EUR
  description: Momentum for cac40
  initial_capital: 10000.0
  name: Momentum cac
  type: paper
- currency: EUR
  description: Test portfolio for development
  initial_capital: 100000.0
  name: Test Portfolio
  type: paper
- currency: EUR
  description: PEA Gilles
  initial_capital: 10000.0
  name: PEA Gilles
  type: paper
- currency: EUR
  description: ''
  initial_capital: 10000.0
  name: Momentum ETF_FR
  type: paper
- currency: EUR
  description: ''
  initial_capital: 10000.0
  name: Momentum ETF PEA Full
  type: paper
