"""Trading broker agent for executing pending orders and managing exits on a specific date."""

from datetime import date as date_type
from typing import Any, Dict, Optional, List
from core.agent import Agent
from tools.portfolio import PortfolioManager
from tools.portfolio.orders import Orders
from tools.portfolio.journal import Journal
from tools.portfolio.execution_helpers import broker_from_journal, get_price, row_to_metadata, trading_datetime
from tools.strategy import StrategyManager
from .sub_agents import (
	StopLossAgent,
	TargetAgent,
	TimeLimitAgent,
	LimitOrderAgent,
	MarketOrderAgent,
)


class TradingBroker(Agent):
	"""Agent for executing pending orders on a specific trading date.

	Executes pending orders generated by OrdersExitAgent and OrdersEntryAgent:
	1. Execute SELL orders (from exit conditions) at market prices
	2. Execute limit orders (conditional BUY orders)
	3. Execute BUY orders (market orders)
	4. Check open positions against stop_loss, take_profit, time limits
	5. Record all transactions in journal
	6. Update portfolio cache
	"""

	def __init__(self, name: str = "TradingBroker", context: Optional[Any] = None):
		"""Initialize trading broker agent.

		Args:
			name: Agent name
			context: AgentContext for shared state
		"""
		super().__init__(name, context)
		self.stop_loss_agent = StopLossAgent("StopLossAgent")
		self.target_agent = TargetAgent("TargetAgent")
		self.time_limit_agent = TimeLimitAgent("TimeLimitAgent")
		self.limit_agent = LimitOrderAgent("LimitOrderAgent")
		self.market_agent = MarketOrderAgent("MarketOrderAgent")

	def process(self, input_data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
		"""Execute pending BUY orders and manage exits (stop_loss) for a specific date.

		Assumes day data has already been loaded by MarketProcessAgent into context.data_history.

		Args:
			input_data: Input data with:
				- date: Trading date (YYYY-MM-DD or date object)
				- portfolio_name: Portfolio to execute orders for

		Returns:
			Response with execution results (BUY and EXIT)
		"""
		if input_data is None:
			input_data = {}

		# Get parameters from context (set by MarketProcessAgent)
		portfolio_name = self.context.get("portfolio_name") or "default"
		trading_date = self.context.get("date")

		if not trading_date:
			return {
				"status": "error",
				"input": input_data,
				"message": "date not set in context"
			}

		# Get pre-sliced day data (already filtered to specific date by BacktestAgent)
		day_data = self.context.get("day_data") or {}
		if not day_data:
			self.logger.warning(f"No day data available for {trading_date}")

		journal = Journal(portfolio_name, context=self.context.__dict__)
		orders_mgr = Orders(portfolio_name, context=self.context.__dict__)

		# Execute SELL orders first (from exit conditions)
		sell_results = self._execute_sell_orders(
			orders_mgr,
			journal,
			portfolio_name,
			trading_date,
			day_data
		)

		# Execute buy orders in priority: limit orders first, then market orders
		buy_results = []

		# 1. Execute limit orders (these stay pending until price condition met)
		limit_result = self._run_sub_agent(self.limit_agent, {"day_data": day_data}, fatal=False)
		buy_results.extend(limit_result.get("output", {}).get("orders", []))

		# 2. Execute market orders (fill immediately at market price)
		market_result = self._run_sub_agent(self.market_agent, {"day_data": day_data}, fatal=False)
		buy_results.extend(market_result.get("output", {}).get("orders", []))

		# Load strategy config once and derive both holding_period and take_profit_enabled from it
		strategy_config = self._load_strategy_config()

		if not self.context.get("holding_period"):
			holding_period = self._extract_holding_period(strategy_config)
			if holding_period:
				self.context.set("holding_period", holding_period)
				self.logger.debug(f"Set holding_period to {holding_period} from strategy config")

		# Execute exit orders via subagents in sequence
		exit_results = []

		# 1. Stop loss exits (uses effective_stop_losses calculated by OrdersExitAgent.StopLossAgent)
		stop_loss_result = self._run_sub_agent(self.stop_loss_agent, {"day_data": day_data}, fatal=False)
		exit_results.extend(stop_loss_result.get("output", {}).get("exits", []))

		# 2. Take profit exits (only if enabled in strategy)
		take_profit_enabled = self._is_take_profit_enabled(strategy_config)
		if take_profit_enabled:
			target_result = self._run_sub_agent(self.target_agent, {"day_data": day_data}, fatal=False)
			exit_results.extend(target_result.get("output", {}).get("exits", []))
		else:
			self.logger.info("Take profit is disabled in strategy, skipping target agent")

		# 3. Time limit exits (unfilled entry orders)
		time_limit_result = self._run_sub_agent(self.time_limit_agent, {"day_data": day_data}, fatal=False)
		exit_results.extend(time_limit_result.get("output", {}).get("exits", []))

		buy_count = len([r for r in buy_results if r.get("status") == "filled"])
		exit_count = len([r for r in exit_results if r.get("status") == "filled"])
		total_executed = buy_count + exit_count

		# Update portfolio cache
		pm = PortfolioManager(context=self.context.__dict__)
		pm.update_portfolio_cache(portfolio_name)

		return {
			"status": "success",
			"input": input_data,
			"output": {
				"portfolio": portfolio_name,
				"date": trading_date.isoformat(),
				"buy_executed": buy_count,
				"exit_executed": exit_count,
				"total_executed": total_executed,
				"buy_details": buy_results,
				"exit_details": exit_results,
			},
			"message": f"Executed {buy_count} BUY + {exit_count} EXIT orders for {portfolio_name}",
		}

	def _execute_sell_orders(
		self,
		orders_mgr: Orders,
		journal: Journal,
		portfolio_name: str,
		trading_date: date_type,
		day_data: Dict[str, Any]
	) -> List[Dict[str, Any]]:
		"""Execute pending SELL orders using market data.

		Handles both market and limit orders:
		- Market SELL orders: executed immediately at market price
		- Limit SELL orders: executed only if price condition met (price <= limit_price)

		Args:
			orders_mgr: Orders manager
			journal: Journal for recording transactions
			portfolio_name: Portfolio name
			trading_date: Date of execution
			day_data: Pre-sliced market data {ticker: row} for the specific date

		Returns:
			List of sell execution results
		"""
		execution_results = []
		broker = broker_from_journal(journal, logger=self.logger)
		# Use get_active_orders() to skip expired orders (trading_date used as current_date)
		active_orders = orders_mgr.get_active_orders(current_date=trading_date)

		if active_orders.empty:
			return execution_results

		# Filter for SELL orders only (operation == "SELL")
		if "operation" in active_orders.columns:
			sell_orders_df = active_orders[active_orders["operation"].str.upper() == "SELL"]
		else:
			# Fallback for legacy orders predating the "operation" column: check metadata
			sell_orders = []
			for _, order_row in active_orders.iterrows():
				if orders_mgr.parse_order_row(order_row)["metadata"].get("order_type") == "SELL":
					sell_orders.append(order_row)
			if sell_orders:
				sell_orders_df = active_orders.loc[active_orders.index.isin([s.name for s in sell_orders])]
			else:
				sell_orders_df = active_orders.iloc[0:0]  # Empty DataFrame with same schema

		if sell_orders_df.empty:
			return execution_results

		execution_time = trading_datetime(trading_date)

		for _, order_row in sell_orders_df.iterrows():
			try:
				order = orders_mgr.parse_order_row(order_row)
				order_id = order["id"]
				ticker = order["ticker"]
				quantity = order["quantity"]
				execution_method = order["execution_method"]
				limit_price = order["limit_price"]

				# Get open price for SELL execution (better price for exits)
				execution_price = get_price(day_data, ticker, "open")
				if execution_price is None:
					# Fallback to close price if open not available
					execution_price = get_price(day_data, ticker, "close")
				if execution_price is None:
					self.logger.warning(f"No market price for {ticker}, skipping SELL order")
					orders_mgr.update_order_status(order_id, "rejected")
					continue

				# Determine execution price based on order type
				if execution_method == "limit":
					# For limit SELL: only execute if execution_price <= limit_price
					if limit_price is None:
						limit_price = order["entry_price"]  # fallback to entry_price

					if execution_price <= limit_price:
						self.logger.debug(f"Limit SELL {ticker}: price {execution_price:.2f} <= limit {limit_price:.2f}, executing")
					else:
						self.logger.debug(f"Limit SELL {ticker}: price {execution_price:.2f} > limit {limit_price:.2f}, skipping")
						orders_mgr.update_order_status(order_id, "pending")
						continue
				# else: Market order - execute at open price (execution_price already set)

				# Convert order for broker
				broker_order = {
					"ticker": ticker,
					"quantity": quantity,
					"action": "SELL",
					"price": execution_price,
					"strategy_id": "transact",
				}

				# Execute through broker
				result = broker.execute_order(broker_order)

				execution_result = {
					"order_id": order_id,
					"ticker": ticker,
					"quantity": quantity,
					"execution_price": execution_price,
					"status": result.status,
					"filled_price": result.filled_price,
					"filled_quantity": result.filled_quantity,
					"reason": result.reason,
				}
				execution_results.append(execution_result)

				# Update order status and record transaction if filled
				if result.status == "filled":
					orders_mgr.update_order_status(order_id, "executed")

					exit_type = order["metadata"].get("exit_type")
					market_metadata = row_to_metadata(day_data.get(ticker))

					# Record SELL transaction in journal with explicit status_at (exit_date)
					journal.add_transaction(
						operation="SELL",
						ticker=ticker,
						quantity=result.filled_quantity,
						price=result.filled_price,
						fees=0,
						notes=f"Order {order_id[:8]} executed",
						created_at=execution_time,
						status_at=execution_time,
						exit_type=exit_type,
						metadata=market_metadata
					)

					self.logger.info(
						f"SELL {result.filled_quantity} {ticker} @ {result.filled_price:.2f} "
						f"({execution_method} order {order_id[:8]})"
					)
				else:
					orders_mgr.update_order_status(order_id, "rejected")
					self.logger.warning(f"SELL Order {order_id[:8]} rejected: {result.reason}")

			except Exception as e:
				self.logger.error(f"Error executing SELL order {order_row.get('id', '')} for {order_row.get('ticker', '')}: {e}")

		return execution_results

	def _load_strategy_config(self) -> Dict[str, Any]:
		"""Load strategy configuration once for this process() call.

		Used to derive both holding_period (time limit exits) and take_profit
		enablement, avoiding two separate StrategyManager.load_strategy() round-trips.

		Returns:
			Strategy config dict, or {} if no strategy_name in context or load fails
		"""
		strategy_name = self.context.get("strategy_name")
		if not strategy_name:
			self.logger.debug("No strategy_name in context, skipping strategy config load")
			return {}

		try:
			result = StrategyManager().load_strategy(strategy_name)
			if result.get("status") != "success":
				self.logger.warning(f"Could not load strategy config for {strategy_name}")
				return {}
			return result.get("data", {}) or {}
		except Exception as e:
			self.logger.warning(f"Error loading strategy config for {strategy_name}: {e}")
			return {}

	def _extract_holding_period(self, strategy_config: Dict[str, Any]) -> Optional[int]:
		"""Extract holding_period (in days) from a loaded strategy config.

		Args:
			strategy_config: Strategy config dict from _load_strategy_config()

		Returns:
			Holding period in days, or None if not configured
		"""
		exit_params = strategy_config.get("exit", {}).get("parameters", {})
		hp_formula = exit_params.get("holding_period", {}).get("formula")
		if not hp_formula:
			return None
		try:
			return int(float(hp_formula))
		except (ValueError, TypeError):
			return None

	def _is_take_profit_enabled(self, strategy_config: Dict[str, Any]) -> bool:
		"""Check if take_profit is enabled in a loaded strategy configuration.

		In backtest mode, reads from the strategy config passed in. With no
		strategy config (e.g. paper trading, or load failed), conservatively
		enables take_profit so TargetAgent still runs.

		Args:
			strategy_config: Strategy config dict from _load_strategy_config()

		Returns:
			True if take_profit should be evaluated, False if disabled
		"""
		if not strategy_config:
			return True

		# Check if take_profit is explicitly disabled
		exit_params = strategy_config.get("exit", {}).get("parameters", {})
		take_profit = exit_params.get("take_profit", {})

		# If formula is 'False' (string) or False (bool), it's disabled
		formula = take_profit.get("formula")
		is_disabled = formula == "False" or formula is False

		self.logger.debug(f"take_profit.formula={repr(formula)}, disabled={is_disabled}")

		return not is_disabled
